require "set"

# This is a module for the *mapredo* MapReduce engine.  This will give
# you much better looking code than running the mapredo commands from
# a shell script, and it is also easier to use and understand.
#
# Author::    Kjell Irgens  (mailto:hextremist@gmail.com)
# Copyright:: Copyright (c) 2015 Kjell Irgens
# License::   LGPLv2

module Mapredo
  @@parent = Hash.new
  @@child = Hash.new

  # This class represents an instance of a map-reduce plugin.  To
  # create new objects, use +Mapredo.make_mapreducer+.
  class Mapreducer
    # Change the number of worker threads
    attr_writer :parallel
    # Set to false to disable compression
    :compression
    # Change the maximum number of open files in the merge stage
    attr_writer :files
    # Change the size of the sort buffer
    attr_writer :buffer
    # Custom root work (temporary) directory
    attr_accessor :workdir
    # Get the name of the mapredo plugin
    attr_reader :name
    # Will the mapredo command run use --map-only?
    attr_reader :map_only

    @@id = 0
    
    # If this mapredo command should take its input from an existing
    # file, use this method.
    # Params:
    # +filename+:: path to input file
    def input_file(filename)
      @input_file = filename
    end

    # If this mapredo command should take its input from the output of another
    # mapredo command, use this method.
    # Params:
    # +mapreducer+:: Previously created Mapreducer object
    def input(mapreducer)
      Mapredo.add_child_requirement(self, mapreducer)
      Mapredo.add_parent_requirement(self, mapreducer)
    end

    # This method is used if the mapredo command should take
    # additional input from another mapper in addition to the +input+
    # method.
    # Params:
    # +mapreducer+:: Previously created Mapreducer object
    def add_mapper(mapreducer)
      mapreducer.map_to_dir "tmpdir#{@id}"
      @map_only = true
      @subdir = "tmpdir#{@id}"
      @reduce_only = true
      Mapredo.add_parent_requirement(self, mapreducer)
    end

    # Returns the command line generated by this object.
    def cmdline
      cmd = add_cmd
      if(@reduce_only)
        cmd += " && " + add_cmd(true)
      end
      cmd
    end

    def map_to_dir(directory)
      raise "Attempt to add #{} as mapper twice" if @map_only
      @map_only = true
      @subdir = directory
    end

    private

    def initialize(name)
      @name = name
      @id = @@id
      @@id += 1
    end

    def add_cmd(reduce_only = false)
      cmd = "mapredo "
      cmd += "-i '#{@input_file}' " if @input_file
      cmd += "-j #{@parallel} " if @parallel
      cmd += "--no-compression " if @compression == false
      cmd += "-b #{@buffer} " if @buffer
      cmd += "-f #{@files} " if @files
      if (reduce_only)
        cmd += "--reduce-only -s #{@subdir} "
      else
        cmd += "--map-only -s #{@subdir} " if @map_only
      end
      cmd += @name
    end
  end

  # Creates a new Mapreducer object.
  # Params:
  # +name+:: the name of the mapredo plugin to use, such as _wordcount_.
  def Mapredo.make_mapreducer(name)
    mr = Mapreducer.send(:new, name)
    @@child[mr] = Set.new
    @@parent[mr] = Set.new
    mr
  end

  # Runs a set of mapredo commands based on the instanciated
  # Mapreducer objects.  This will use temporary files where needed,
  # and otherwise provide the mapredo commands with the necessary
  # arguments.
  def Mapredo.run
    if (@parallel)
      @@child.each do |mr,children|
        mr.parallel = @parallel
      end
    end

    cmdlines = Array.new
    done = Set.new

    while done.size < @@child.size
      @@child.each do |mr,children|
        if !done.include?(mr) && requirements_done(nil, mr, done)
          cmdlines.push build_cmdline(mr, children, done)
        end
      end
    end

    if done.empty?
      raise "Nothing to do"
    end

    cmdlines.each do |cmd|
      $stderr.puts cmd
      system cmd
      break if $? != 0
    end
  end

  # Set the default number of worker threads for all mapredo commands.
  # Params:
  # +jobs+:: positive number representing the number of threads
  def Mapredo.parallel(jobs)
    @parallel = jobs.to_int
    raise "Parallel must be a positive integer" if @parallel < 1
    ENV['MAPREDO_PARALLEL'] = jobs
  end

  private

  def Mapredo.add_parent_requirement (to, from)
    @@parent[to].add from
  end

  def Mapredo.add_child_requirement (to, from)
    children = @@child[from]
    if (!children)
      raise "Unknown mapreducer"
    end
    children.add to
  end

  def Mapredo.build_cmdline(mapreducer, children, done)
    cmd = ""
    if children.empty?
      cmd = mapreducer.cmdline
    elsif children.size == 1
      cmd = "#{mapreducer.cmdline} | " \
            + "#{build_cmdline(children.first, @@child[children.first], done)}"
    else
      cmd = "#{mapreducer.cmdline} > tmpfile#{@id}.txt"
      children.each do |mr|
        mr.input_file "tmpfile#{@id}.txt"
      end
    end
    done.add mapreducer
    cmd
  end

  def Mapredo.requirements_done (parent, mapreducer, done)
    @@parent[mapreducer].each do |par|
      return nil if(par != parent && !done.member?(par))
    end

    children = @@child[mapreducer]
    if(children.size == 1)
      #return true if(children.first.map_only)
      return requirements_done(mapreducer, children.first, done)
    else
      return true
    end
  end

end
